repos:
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      language_version: python3.8
      args:
        - "--line-length=88"
      exclude: ^generated/
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args:
        - "--max-line-length=88"
        - "--ignore=E203,E266,F401,E402,F403,E501,W503"
      exclude: ^generated/|orchestrator/fedavg.mp-spdz.py
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
    - id: mdformat
      args:
        - --wrap
        - "80"
      additional_dependencies:
        - mdformat-gfm
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
    - id: markdownlint
