- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
    - id: mdformat
      args:
      - --wrap
      - "80"
      additional_dependencies:
        - mdformat-gfm
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
    - id: markdownlint
