import math

import torch

# Single precision parameters for sfloat
vlen = 24
plen = 8


# Converts a Python float into a MP-SPDZ sfloat.
#
# Taken from the MP-SPDZ codebase with return type changed to array.
def float_to_sfloat(v):
    if v < 0:
        s = 1
    else:
        s = 0
    if v == 0:
        v = 0
        p = 0
        z = 1
    else:
        p = int(math.floor(math.log(abs(v), 2))) - vlen + 1
        vv = v
        v = int(round(abs(v) * 2 ** (-p)))
        if v == 2 ** vlen:
            p += 1
            v //= 2
        z = 0
        if p < -2 ** (plen - 1):
            print('Warning: %e truncated to zero' % vv)
            v, p, z = 0, 0, 1
        if p >= 2 ** (plen - 1):
            raise Exception('Cannot convert %s to float with %d exponent bits' % (vv, plen))
    return [v, p, z, s]


def encode_sfloat(v, p, z, s):
    """Encodes a 4-tuple into a 3-tuple sfloat by packing the zero and sign bits into a single element"""
    return [v, p, z + s * 2]


def decode_sfloat(v, p, zs):
    """Decodes a 3-tuple sfloat generated by encode into a 4-tuple"""
    return [v, p, zs % 2, zs >> 1]


# Converts a torch.float32 tensor into an array of MP-SPDZ sfloats.
def float32_tensor_to_sfloat_array(tensor, shift=False):
    assert tensor.dtype == torch.float32
    f = torch.flatten(tensor)
    sfloats = []
    for _, f in enumerate(f):
        sfloat = float_to_sfloat(f.item())
        if shift:
            sfloat[0] += 2 ** vlen
            sfloat[1] += 2 ** plen
        sfloats.append(encode_sfloat(*sfloat))
    return sfloats


# Converts a MP-SPDZ sfloat to a Python float.
def sfloat_to_float(v, p, z, s):
    return (1-2*s)*(1-z)*v*math.pow(2, p)


# Converts an array of MP-SPDZ sfloats into a float32 tensor of the given shape.
def sfloat_array_to_float32_tensor(values, shape, shift=False):
    tv = []
    for v in values:
        if shift:
            v[0] -= 2 ** vlen
            v[1] -= 2 ** plen
        tv.append(sfloat_to_float(*decode_sfloat(*v)))
    return torch.reshape(torch.tensor(tv), shape)
