#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/nettle.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Perform Tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m venv .venv/
          source .venv/bin/activate
          pip install pip-tools
          pip-sync
      - name: Build Docker Image
        run: |
          make mp-spdz-mpc-client
      - name: Perform Tests
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
          PYTHONPATH: .
        run: |
          source .venv/bin/activate
          pip install pytest pytest-cov
          pytest
